# Omakase Ruby styling for Rails
inherit_gem:
  { rubocop-rails-omakase: rubocop.yml }

  # Overwrite or add rules to create your own house style
  #
  # # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
  # Layout/SpaceInsideArrayLiteralBrackets:
  #   Enabled: false

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

RSpec/MessageSpies:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

RSpec/ExampleLength:
  Max: 25

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

RSpec/StubbedMock:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/ClassLength:
  Max: 200

RSpec/ExampleLength:
  Max: 40

Rails/BulkChangeTable:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 50
