REDIS_URL: redis://localhost:6379/0

# generate using: rails db:encryption:init
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ""
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ""
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ""

EXCHANGE_BACKEND_DOMAIN: "snowfoxglobal.org"
AWS_SES_SMTP_ENDPOINT: "email-smtp.us-east-1.amazonaws.com"
AWS_SES_SMTP_PORT: 587
AWS_SES_SMTP_USERNAME: ""
AWS_SES_SMTP_PASSWORD: ""

ROLLBAR_ACCESS_TOKEN: ""
EXCHANGE_BACKEND_DOMAIN: "localhost:3969"

ROLLBAR_ACCESS_TOKEN: ""
KAFKA_BROKER: "127.0.0.1:9092"

GOOGLE_CLIENT_ID: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
GOOGLE_CLIENT_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

COIN_PORTAL_VERIFYING_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
EXCHANGE_SIGNING_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
COIN_PORTAL_URL: "http://localhost:3000"