name: Zeitwerk Check

on:
  push:
    branches: ["main", "staging"]
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  zeitwerk:
    name: Zeitwerk Check
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Check Zeitwerk
        run: bundle exec rake zeitwerk:check
